[metadata]
name = edge_sdk
version = 0.5
description = mellerikat edge
author = Mellerikat
author_email = contact@mellerikat.com
url = https://mellerikat.com

[options]
packages = find:
package_dir =
    = src
install_requires =
    requests
    websockets
    pandas
    loguru
    PyYAML
    psutil
    nest_asyncio

[options.packages.find]
where = src